name: GradientBasedLearningForCAP
version: "2026.01-02"
license: "GPL-2.0-or-later"
date: 2026-01-21
description: |
    Gradient Based Learning via Category Theory

authors:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

maintainers:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

GAP: ">= 4.13.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2024.09-12"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2024.04-01"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "CartesianCategories"
      version: ">= 2024.04-01"
      url: "https://homalg-project.github.io/pkg/CartesianCategories"
    - name: "ToolsForCategoricalTowers"
      version: ">= 2024.06-02"
      url: "https://homalg-project.github.io/pkg/ToolsForCategoricalTowers"

suggested-pkgs:
    - name: "ToolsForHigherHomologicalAlgebra"
      version: ">= 2023.01-01"

www: https://homalg-project.github.io/pkg/GradientBasedLearningForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/GradientBasedLearningForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/GradientBasedLearningForCAP/releases/download/v2026.01-02/GradientBasedLearningForCAP-2026.01-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/GradientBasedLearningForCAP/releases/download/v2026.01-02/GradientBasedLearningForCAP-2026.01-02.zip

pdf: https://github.com/homalg-project/GradientBasedLearningForCAP/releases/download/v2026.01-02/GradientBasedLearningForCAP-2026.01-02-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Explore Categorical Machine Learning.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Sal21</span>]   <b class='BibAuthor'>Saleh, K.</b>,
     <i class='BibTitle'>GradientBasedLearningForCAP, Gradient Based Learning via Category Theory,
             Version 2026.01-02</i>
     (<span class='BibYear'>1-21</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/GradientBasedLearningForCAP">https://homalg-project.github.io/pkg/GradientBasedLearningForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ GradientBasedLearningForCAP,
      author =           {Saleh, K.},
      title =            {{GradientBasedLearningForCAP},     {Gradient     Based
                          Learning     via     Category    Theory},    {V}ersion
                          2026.01\texttt{\symbol{45}}02},
      month =            {6\texttt{\symbol{45}}},
      year =             {1\texttt{\symbol{45}}21},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/GradientBasedLearningForCAP}
                          {\texttt{https://homalg\texttt{\symbol{45}}project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{GradientBasedLearningForCAP}}},
      keywords =         {Explore Categorical Machine Learning},
      printedkey =       {Sal21}
    }

