name: GradientDescentForCAP
version: "2025.11-01"
license: "GPL-2.0-or-later"
date: 2025-11-28
description: |
    Exploring categorical machine learning in CAP

authors:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

maintainers:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

GAP: ">= 4.15.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2024.09-12"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2024.04-01"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "CartesianCategories"
      version: ">= 2024.04-01"
      url: "https://homalg-project.github.io/pkg/CartesianCategories"
    - name: "ToolsForCategoricalTowers"
      version: ">= 2024.06-02"
      url: "https://homalg-project.github.io/pkg/ToolsForCategoricalTowers"

suggested-pkgs:
    - name: "ToolsForHigherHomologicalAlgebra"
      version: ">= 2023.01-01"

www: https://homalg-project.github.io/pkg/GradientDescentForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/GradientDescentForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/GradientDescentForCAP/releases/download/v2025.11-01/GradientDescentForCAP-2025.11-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/GradientDescentForCAP/releases/download/v2025.11-01/GradientDescentForCAP-2025.11-01.zip

pdf: https://github.com/homalg-project/GradientDescentForCAP/releases/download/v2025.11-01/GradientDescentForCAP-2025.11-01-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Explore Categorical Machine Learning.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Sal28</span>]   <b class='BibAuthor'>Saleh, K.</b>,
     <i class='BibTitle'>GradientDescentForCAP, Exploring categorical machine learning in CAP,
             Version 2025.11-01</i>
     (<span class='BibYear'>1-28</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/GradientDescentForCAP">https://homalg-project.github.io/pkg/GradientDescentForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ GradientDescentForCAP,
      author =           {Saleh, K.},
      title =            {{GradientDescentForCAP},     {Exploring    categorical
                          machine      learning      in      CAP},     {V}ersion
                          2025.11\texttt{\symbol{45}}01},
      month =            {5\texttt{\symbol{45}}},
      year =             {1\texttt{\symbol{45}}28},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/GradientDescentForCAP}
                          {\texttt{https://homalg\texttt{\symbol{45}}project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{GradientDescentForCAP}}},
      keywords =         {Explore Categorical Machine Learning},
      printedkey =       {Sal28}
    }

